#!/bin/bash

# Check if a YouTube link is provided as an argument and assigned values

link=$1

case "$(echo $XDG_SESSION_TYPE)" in
  "wayland") copy="wl-copy" && paste="wl-paste"
  ;;
  "x11") copy="xclip -selection clipboard" && paste="xclip -o -selection clipboard"
  ;;
  *) copy="termux-clipboard-get" && paste="termux-clipboard-set"
  ;;
esac

[ $# -eq 0 ] && link=$($paste) && clip="True"

[ "$link" != "$1" ] && check=$(grep -e "youtube" -e "youtu.be" <<< $link) || check=$(grep -e "youtube" -e "youtu.be" <<< $1) 

[ -z "$check" ] && echo "Please provide valid youtube link" && exit 1

# Extract the video ID and start time (if present) from the YouTube link
if echo $link | grep -q "youtube.com"; then
  video_id=$(echo $link | sed 's/.*v=\(.*\)/\1/')
  start_time=$(echo $link | grep -o "t=[^&]*" | sed 's/t=//')
else
  video_id=$(echo $link | sed 's/.*\/\(.*\)/\1/')
  start_time=$(echo $link | grep -o "t=[^&]*" | sed 's/t=//')
fi

# Generate the iframe code with the video ID and start time (if present)
iframe="<iframe width=\"200\" height=\"113\" src=\"https://www.youtube.com/embed/${video_id}"

[ -n "$start_time" ] && iframe="${iframe}?start=${start_time}"

iframe="${iframe}\" style=\"aspect-ratio: 1.76991 / 1; width: 100%; height: 100%;\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen=\"\" allow=\"fullscren\"></iframe>"

# Print the iframe code
[ "$clip" = "True" ] && echo $iframe | $copy && exit 1

echo $iframe
